### ISSUE TITLE
dump on seeking game

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#18]
hi, lately i seek 3 5 f and wait and after somesec
the crash always.
papageorge:1925): Gtk-CRITICAL **: gtk_main_quit: assertion 'main_loops != NULL' failed

**Comment by drestebon** [comment]
I added an option in the configuration to enable logging

It would be great if you could reproduce the crash and get the relevant part of the log here

**Comment by enricoT** [comment]
after latest update i have this on login
Traceback (most recent call last):
  File "/usr/bin/papageorge", line 53, in <module>
    papageorge.run(fics_user, fics_pass)
  File "/usr/lib/python3.4/site-packages/papageorge/**init**.py", line 44, in run
    cli = CLI(fics_user, fics_pass, log)
  File "/usr/lib/python3.4/site-packages/papageorge/cli.py", line 236, in **init**
    for restring, hcolor in config.console.highlight:
ValueError: need more than 1 value to unpack

this is at good time when i was able to run papageorge :)
:02:47 b'fics% \n'
2015-10-01 15:02:47 b'GuestMSCX accepts your seek.\n'
2015-10-01 15:02:47 b'\n'
2015-10-01 15:02:47 b'Creating: AcCoNcIo (1339) GuestMSCX (++++) unrated blitz 3 10\n'
2015-10-01 15:02:47 b'{Game 166 (AcCoNcIo vs. GuestMSCX) Creating unrated blitz match.}\n'
2015-10-01 15:02:47 b'\n'
2015-10-01 15:02:47 b'<g1> 166 p=0 t=blitz r=0 u=0,1 it=180,10 i=180,10 pt=0 rt=1339E,0P ts=0,1 m=2 n=1\n'
2015-10-01 15:02:47 b'\n'
2015-10-01 15:02:47 b'<12> rnbqkbnr pppppppp -------- -------- -------- -------- PPPPPPPP RNBQKBNR W -1 1 1 1 1 0 166 AcCoNcIo GuestMSCX 1 3 10 39 39 180 180 1 none (0:00) none 0 0 0\n'
2015-10-01 15:02:47 b'fics% \n'
2015-10-01 15:02:47 b'Game 166: A disconnection will be considered a forfeit.\n'
2015-10-01 15:02:47 EXCEPTION IN (/usr/lib/python3.4/site-packages/papageorge/**init**.py, LINE 47 "cli.connect_mainloop()"): 'tuple' object is not callable
Traceback (most recent call last):
File "/usr/lib/python3.4/site-packages/papageorge/**init**.py", line 47, in run
cli.connect_mainloop()
File "/usr/lib/python3.4/site-packages/papageorge/cli.py", line 446, in connect_mainloop
self.main_loop.run()
File "/usr/lib/python3.4/site-packages/urwid/main_loop.py", line 278, in run
self._run()
File "/usr/lib/python3.4/site-packages/urwid/main_loop.py", line 375, in _run
self.event_loop.run()
File "/usr/lib/python3.4/site-packages/urwid/main_loop.py", line 847, in run
raise exc_info[0](exc_info[1]).with_traceback(exc_info[2])
File "/usr/lib/python3.4/site-packages/urwid/main_loop.py", line 860, in wrapper
return f(_args,_*kargs)
File "/usr/lib/python3.4/site-packages/urwid/main_loop.py", line 780, in io_callback
callback()
File "/usr/lib/python3.4/site-packages/urwid/main_loop.py", line 224, in cb
rval = callback(data)
File "/usr/lib/python3.4/site-packages/papageorge/cli.py", line 435, in read_pipe
self.print(line)
File "/usr/lib/python3.4/site-packages/papageorge/cli.py", line 400, in print
txt = rule[1](regxp, text)
File "/usr/lib/python3.4/site-packages/papageorge/cli.py", line 330, in style12
b.set_state(txt)
File "/usr/lib/python3.4/site-packages/papageorge/gui.py", line 496, in set_state
self.pop = BoardCommandsPopover(self)
File "/usr/lib/python3.4/site-packages/papageorge/gui.py", line 336, in __init__
('R_efresh',   lambda x : 'refresh'),
TypeError: 'tuple' object is not callable

2015-10-01 15:02:48 b'fics% Finger of AcCoNcIo:\n'
