### ISSUE TITLE
error on login

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#20]
after password and login
Traceback (most recent call last):
  File "/usr/bin/papageorge", line 53, in <module>
    papageorge.run(fics_user, fics_pass)
  File "/usr/lib/python3.4/site-packages/papageorge/**init**.py", line 44, in run
    cli = CLI(fics_user, fics_pass, log)
  File "/usr/lib/python3.4/site-packages/papageorge/cli.py", line 236, in **init**
    for restring, hcolor in config.console.highlight:
ValueError: need more than 1 value to unpack

**Comment by drestebon** [comment]
what do you have in your ~/.papageorge.conf  ??
