### ISSUE TITLE
add .desktop, icon and maybe steal create_deb.sh from pychess?

### ISSUE THREAD

**Issue by enricoT** [drestebon/papageorge#26]
xfce4-terminal -H -x papageorge $(head /home/enrico/icsrc)
this works on terminal

this is from launcher
*\* (papageorge:16350): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
$(head /home/enrico/icsrc)
Traceback (most recent call last):
  File "/usr/sbin/papageorge", line 59, in <module>
    papageorge.run(config.fics_user, fics_pass)
  File "/usr/lib/python3.4/site-packages/papageorge/**init**.py", line 44, in run
    cli = CLI(fics_user, fics_pass, log)
  File "/usr/lib/python3.4/site-packages/papageorge/cli.py", line 264, in **init**
    self.hl_rule = re.compile(highlight)
  File "/usr/lib/python3.4/re.py", line 223, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.4/re.py", line 294, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.4/sre_compile.py", line 568, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.4/sre_parse.py", line 760, in parse
    p = _parse_sub(source, pattern, 0)
  File "/usr/lib/python3.4/sre_parse.py", line 370, in _parse_sub
    itemsappend(_parse(source, state))
  File "/usr/lib/python3.4/sre_parse.py", line 710, in _parse
    raise error("unbalanced parenthesis")
sre_constants.error: unbalanced parenthesis

**Comment by enricoT** [comment]
making a ./pg.sh with inside xfce4-terminal -H -x papageorge $(head /home/enrico/icsrc) work out ,
this is .desktop in /usr/share/applications:
[Desktop Entry]
Type=Application
Version=1.0
Name=papageorge
GenericName=Chess Fics Client
Icon=papageorge.png
Exec=./pg.sh
Categories=Game;BoardGame;
![papageorge](https://cloud.githubusercontent.com/assets/5571974/10258731/eddd976e-6960-11e5-9aaf-3dac819f8ae2.png)
 papageorge.png is in /usr/share/pixmaps like eboard.png for example i think is standard if not /usr/local/share/pixmaps or whatever im not skilled in AUR rules

**Comment by enricoT** [comment]
a .deb to download would be great for debian/ubuntu users, wich are the big amount of fics users :+1: 
it's complicate for me to teach how to run papageorge to an ubuntu user, they want the icon to click or they skip the package as useless.
